name: kidly_clone
description: "Kidly Clone App"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  qr_flutter: ^4.1.0
  url_launcher: ^6.2.5
  webview_flutter: ^4.7.0
  # Theme state save rakhne ke liye
  shared_preferences: ^2.2.2
  # Text ko audio me padhne ke liye
  flutter_tts: ^3.8.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/
